# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # users and products repositories for deployment
    App\Interfaces\IUsersRepository: '@UsersRepository'
    App\Interfaces\IProductsRepository: '@ProductsRepository'

    # users and products repositories for testing
    # App\Interfaces\IUsersRepository: '@UsersTestRepository'
    # App\Interfaces\IProductsRepository: '@ProductsTestRepository'

    # -------- repositories --------
    UsersRepository:
        class: App\Repository\UsersRepository

    ProductsRepository:
        class: App\Repository\ProductsRepository

    UsersTestRepository:
        class: App\Repository\UsersTestRepository

    ProductsTestRepository:
        class: App\Repository\ProductsTestRepository
    # ------------------------------

    CreateUserService:
        class: App\CreateUser

    CreateProductService:
        class: App\CreateProduct

    UserIdValidatorService:
        class: App\UserIdValidator

    DomesticAddressValidatorService:
        class: App\DomesticAddressValidator

    StreetValidatorService:
        class: App\StreetValidator

    StateValidatorService:
        class: App\StateValidator

    CountryValidatorService:
        class: App\CountryValidator

    ZipCodeValidatorService:
        class: App\ZipCodeValidator

    PhoneValidatorService:
        class: App\PhoneValidator
    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
